# Generated by Django 2.2.19 on 2024-08-24 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_createpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatePost',
        ),
    ]
